import { chromium } from 'playwright';
const [,, w='844', h='390', tag='dl'] = process.argv;
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome', args: ['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader','--ignore-gpu-blocklist'] });
const page = await browser.newPage({ viewport: { width: +w, height: +h }, deviceScaleFactor: 1, hasTouch: true, isMobile: true });
await page.addInitScript(() => { localStorage.setItem('rxshift_settings_v1', JSON.stringify({ quality: 'low', acceptedNotice: true })); });
await page.goto('http://localhost:5173/', { waitUntil: 'load' });
await page.waitForFunction(() => window.__game, null, { timeout: 60000 });
await page.getByText(/Start first shift|Continue shift/).first().click();
await page.getByRole('button', { name: 'Start' }).click();
await page.evaluate(() => window.__game.jumpToLevel(4));
await page.getByRole('button', { name: 'Start' }).click();
await page.evaluate(async () => { const g = window.__game; const m = await import('/src/data/scenarios.js'); g.customers.spawnTimer = 999; g.customers.spawn(m.SCENARIOS.find(s => s.id === 'S15')); for (let i = 0; i < 30 * 15; i++) g.update(1/30); g.startConsultation(g.customers.counterCust); for (let i = 0; i < 30 * 5; i++) g.update(1/30); });
await page.waitForTimeout(600);
const r = await page.evaluate(async () => { const g = window.__game; for (let i = 0; i < 30 * 3; i++) g.update(1/30); const THREE = await import('/node_modules/.vite/deps/three.js').catch(() => null);
  const pr = (o, y) => { const v = o.group.position.clone(); v.y = y; v.project(g.camera); return [Math.round((v.x + 1) / 2 * innerWidth), Math.round((1 - v.y) / 2 * innerHeight)]; };
  const c = g.customers.counterCust; return { mode: g.mode, cust: pr(c.char, c.char.P.H - 0.12), kid: c.child ? pr(c.child, c.child.P.H - 0.1) : null, pharm: pr(g.player, 1.55), cam: g.camera.position.toArray().map(x => +x.toFixed(2)), pp: g.player.group.position.toArray().map(x=>+x.toFixed(2)), cp: c.char.group.position.toArray().map(x=>+x.toFixed(2)) }; });
console.log(JSON.stringify(r));
await page.screenshot({ path: `/tmp/claude-0/shots/${tag}.png` });
await browser.close();
