import { chromium } from 'playwright';
const [,, w='844', h='390', tag='land'] = process.argv;
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome', args: ['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader','--ignore-gpu-blocklist'] });
const page = await browser.newPage({ viewport: { width: +w, height: +h }, deviceScaleFactor: 1, hasTouch: true, isMobile: true });
await page.addInitScript(() => { try { const k = 'rxshift_settings_v1'; const s = JSON.parse(localStorage.getItem(k) || '{}'); s.quality = 'low'; s.lang = s.lang || 'en'; s.voiceDialogue = false; localStorage.setItem(k, JSON.stringify(s)); } catch (e) {} });
const logs = [];
page.on('console', m => { if (m.type() === 'error' || m.type() === 'warning') logs.push(m.type() + ': ' + m.text()); });
page.on('pageerror', e => logs.push('PAGEERROR: ' + e.message + '\n' + e.stack));
const out = (n) => `/tmp/claude-0/shots/${tag}_${n}.png`;
const sim = (sec) => page.evaluate((s) => { const g = window.__game; for (let i = 0; i < s * 30; i++) g.update(1 / 30); }, sec);
await page.goto('http://localhost:5173/', { waitUntil: 'load' });
await page.waitForFunction(() => window.__game, null, { timeout: 60000 });
await page.waitForTimeout(800);
await page.screenshot({ path: out('01_title') });
await page.getByText('Start first shift').click();
await page.waitForTimeout(500);
await page.screenshot({ path: out('02_notice') });
await page.getByText('I understand').click();
await page.waitForTimeout(400);
await page.screenshot({ path: out('03_levelintro') });
await page.getByRole('button', { name: 'Start' }).click();
if (await page.getByText('Got it').count()) await page.getByText('Got it').click();
await sim(1.5);
await page.waitForTimeout(300);
await page.screenshot({ path: out('04_play') });
// Level 1: visit counter via API tap on interactable
await page.evaluate(() => { const g = window.__game; g.interact(g.world.interactables.find(i => i.id === 'fridge')); });
await sim(6);
await page.screenshot({ path: out('05_fridge') });
await page.evaluate(() => { const g = window.__game; g.ui.closeAll(); g.jumpToLevel(5); });
await page.waitForTimeout(300);
await page.getByRole('button', { name: 'Start' }).click();
await page.evaluate(() => { const g = window.__game; const scn = (window.__scn = null); });
await page.evaluate(() => { const g = window.__game; import('/src/data/scenarios.js').then(m => { g.customers.spawn(m.SCENARIOS.find(s => s.id === 'S23')); }); });
await page.waitForTimeout(500);
await sim(14);
await page.screenshot({ path: out('06_customer_at_counter') });
await page.evaluate(() => { const g = window.__game; g.startConsultation(g.customers.counterCust); });
await sim(3);
await page.waitForTimeout(400);
await page.screenshot({ path: out('07_dialogue') });
await page.evaluate(() => { const g = window.__game; g.ask('duration'); });
await sim(1);
await page.evaluate(() => { const g = window.__game; g.ask('allergies'); });
await sim(1);
await page.waitForTimeout(300);
await page.screenshot({ path: out('08_asked') });
await page.evaluate(() => window.__game.openCabinet());
await page.waitForTimeout(500);
await page.fill('input[type=search]', 'headache');
await page.waitForTimeout(600);
await page.screenshot({ path: out('09_inventory') });
// open first ibuprofen product info
await page.fill('input[type=search]', 'ibuprofen 200');
await page.waitForTimeout(500);
await page.locator('.prow').first().click();
await page.waitForTimeout(400);
await page.screenshot({ path: out('10_medinfo') });
await page.getByText('VIEW DETAILS').click();
await page.waitForTimeout(300);
await page.screenshot({ path: out('11_details') });
await page.getByText('ADD TO CUSTOMER').click();
await page.waitForTimeout(300);
await page.locator('.modal.full .xbtn').click();
await page.waitForTimeout(300);
await page.evaluate(() => window.__game.openSafetyCheck());
await page.waitForTimeout(500);
await page.screenshot({ path: out('12_safety') });
await page.getByText('DISPENSE', { exact: true }).click();
await page.waitForTimeout(500);
await page.screenshot({ path: out('13_counsel') });
await page.locator('.opt').first().click();
await page.getByText('Explain to customer').click();
await sim(1.5);
await page.waitForTimeout(500);
await page.screenshot({ path: out('14_outcome') });
console.log(logs.join('\n'));
await browser.close();
