import { chromium } from 'playwright';
const [,, w='844', h='390', tag='f3'] = process.argv;
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome', args: ['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader','--ignore-gpu-blocklist'] });
const page = await browser.newPage({ viewport: { width: +w, height: +h }, deviceScaleFactor: 1, hasTouch: true, isMobile: true });
await page.addInitScript(() => { try { const k = 'rxshift_settings_v1'; const s = JSON.parse(localStorage.getItem(k) || '{}'); s.quality = 'low'; s.lang = s.lang || 'en'; s.voiceDialogue = false; localStorage.setItem(k, JSON.stringify(s)); } catch (e) {} });
const logs = [];
page.on('console', m => { if (m.type() === 'error' || m.type() === 'warning' || m.text().startsWith('INFO')) logs.push(m.type() + ': ' + m.text()); });
page.on('pageerror', e => logs.push('PAGEERROR: ' + e.message + '\n' + e.stack));
const out = (n) => `/tmp/claude-0/shots/${tag}_${n}.png`;
const sim = (sec) => page.evaluate((s) => { const g = window.__game; for (let i = 0; i < s * 30; i++) g.update(1 / 30); }, sec);
await page.goto('http://localhost:5173/', { waitUntil: 'load' });
await page.waitForFunction(() => window.__game, null, { timeout: 60000 });
await page.evaluate(() => { localStorage.clear(); window.__game.settings.acceptedNotice = true; });
await page.getByText('Start first shift').click();
await page.getByRole('button', { name: 'Start' }).click();
if (await page.getByText('Got it').count()) await page.getByText('Got it').click();
await page.evaluate(() => { const g = window.__game; g.jumpToLevel(6); });
await page.getByRole('button', { name: 'Start' }).click();
await page.waitForTimeout(300);
await sim(1);
await page.screenshot({ path: out('01_level6_shortage') });
// open POS orders and restock syrups
await page.evaluate(() => { const g = window.__game; g.customers.spawnTimer = 999; g.interact(g.world.interactables.find(i => i.id === 'pos')); });
await sim(8); await page.waitForTimeout(400);
await page.screenshot({ path: out('02_pos_orders') });
await page.evaluate(() => { const g = window.__game; g.restock('syrups'); g.ui.closeAll(); });
// trigger fridge event and handle
await page.evaluate(() => { const g = window.__game; g.activeEvent = null; g.triggerEvent('fridge'); });
await sim(0.5);
await page.screenshot({ path: out('03_fridge_alarm') });
await page.evaluate(() => { const g = window.__game; g.interact(g.world.interactables.find(i => i.id === 'fridge')); });
await sim(8); await page.waitForTimeout(500);
await page.screenshot({ path: out('04_fridge_event') });
await page.locator('.opt').first().click();
await page.getByText('Confirm action').click();
await page.waitForTimeout(400);
await page.screenshot({ path: out('05_event_result') });
await page.getByRole('button', { name: 'Continue' }).click();
// shelf inspection w/ highlight
await page.evaluate(() => { const g = window.__game; g.interact(g.world.interactables.find(i => i.section === 'syrups')); });
await sim(8); await page.waitForTimeout(500);
await page.screenshot({ path: out('06_shelf') });
await page.evaluate(() => window.__game.ui.closeAll());
await sim(1);
// LOD debug view
await page.evaluate(() => { const g = window.__game; g.settings.lodDebug = true; g.applySettings(false); g.rig.yaw = Math.PI; g.rig.pitch = 0.35; });
await sim(1.5);
await page.screenshot({ path: out('07_lod_debug') });
await page.evaluate(() => { const g = window.__game; g.settings.lodDebug = false; g.applySettings(false); });
// customer payment flow
await page.evaluate(async () => { const g = window.__game; const m = await import('/src/data/scenarios.js'); g.customers.spawn(m.SCENARIOS.find(s => s.id === 'S01')); });
await sim(14);
await page.evaluate(() => { const g = window.__game; g.startConsultation(g.customers.counterCust); });
await sim(7); await page.waitForTimeout(500);
const st = await page.evaluate(() => { const g = window.__game; return { mode: g.mode, ac: !!g.activeCustomer, cc: g.customers.counterCust && g.customers.counterCust.state, scn: g.customers.counterCust && g.customers.counterCust.scn.id }; });
console.log('INFO state', JSON.stringify(st));
await page.evaluate(() => { const g = window.__game; const p = g.catalog.find(p => p.baseKey === 'paracetamol' && p.form === 'Tablet' && p.stock > 0 && !p.expired); g.markViewed(p); g.addToTray(p); g.beginCounsel({ type: 'dispense' }); });
await page.waitForTimeout(400);
await page.evaluate(() => { const opts=[...document.querySelectorAll('.opt')]; const i = opts.findIndex(o=>/contains Paracetamol/i.test(o.textContent)); (opts[i] || opts[0]).click(); });
await page.getByText('Explain to customer').click();
await page.waitForTimeout(1600);
await page.screenshot({ path: out('08_outcome') });
await page.getByRole('button', { name: 'Continue' }).click();
await sim(6);
await page.evaluate(() => { const g = window.__game; g.interact(g.world.interactables.find(i => i.id === 'pos')); });
await sim(4); await page.waitForTimeout(400);
await page.screenshot({ path: out('09_pos_checkout') });
await page.getByText('COMPLETE TRANSACTION').click();
await page.waitForTimeout(200);
await sim(1); await page.waitForTimeout(1500); await sim(0.5);
await page.screenshot({ path: out('10_paying') });
await page.waitForTimeout(2500); await sim(6);
await page.screenshot({ path: out('11_after_pay') });
// menus
await page.evaluate(() => window.__game.ui.showSettings());
await page.waitForTimeout(300);
await page.screenshot({ path: out('12_settings') });
await page.evaluate(() => { window.__game.ui.closeAll(); window.__game.ui.showTraining(); });
await page.waitForTimeout(300);
await page.screenshot({ path: out('13_training') });
await page.evaluate(() => { window.__game.ui.closeAll(); window.__game.ui.showLevels(); });
await page.waitForTimeout(300);
await page.screenshot({ path: out('14_levels') });
const info = await page.evaluate(() => { const g = window.__game; g.ui.closeAll(); g.renderer.render(g.scene, g.camera); return { calls: g.renderer.info.render.calls, tris: g.renderer.info.render.triangles, geos: g.renderer.info.memory.geometries, tex: g.renderer.info.memory.textures, progs: g.renderer.info.programs.length, money: g.state.money, served: g.state.served, obj: g.state.levelObjectives }; });
console.log('INFO', JSON.stringify(info));
console.log(logs.join('\n'));
await browser.close();
