import { chromium } from 'playwright';
const [,, q='ultra', w='1280', h='720'] = process.argv;
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome', args: ['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader','--ignore-gpu-blocklist'] });
const page = await browser.newPage({ viewport: { width: +w, height: +h }, deviceScaleFactor: 1 });
const logs = [];
page.on('pageerror', e => logs.push('PAGEERROR: ' + e.message));
page.on('console', m => { if (m.type() === 'error' && !m.text().includes('404')) logs.push(m.text()); });
await page.goto('http://localhost:5173/', { waitUntil: 'load' });
await page.waitForFunction(() => window.__game, null, { timeout: 60000 });
await page.evaluate((q) => { const g = window.__game; g.settings.acceptedNotice = true; g.settings.quality = q; g.applySettings(false); }, q);
await page.getByText(/Start first shift|Continue shift/).first().click();
await page.getByRole('button', { name: 'Start' }).click();
await page.evaluate(async () => { const g = window.__game; g.jumpToLevel(4); });
await page.getByRole('button', { name: 'Start' }).click();
await page.evaluate(async () => { const g = window.__game; const m = await import('/src/data/scenarios.js'); g.customers.spawnTimer = 999; g.customers.spawn(m.SCENARIOS.find(s => s.id === 'S15')); g.customers.spawn(m.SCENARIOS.find(s => s.id === 'S10')); for (let i = 0; i < 30 * 16; i++) g.update(1/30); g.rig.yaw = Math.PI * 0.92; g.rig.pitch = 0.22; g.rig.dist = 3.6; for (let i = 0; i < 40; i++) g.update(1/30); });
await page.waitForTimeout(1500);
await page.screenshot({ path: `/tmp/claude-0/shots/q_${q}.png` });
const info = await page.evaluate(() => { const g = window.__game; return { pr: g.pr, calls: g.renderer.info.render.calls, tris: g.renderer.info.render.triangles, shadow: g.renderer.shadowMap.enabled, bloom: g.bloom }; });
console.log(q, JSON.stringify(info), logs.join('\n'));
await browser.close();
